### ISSUE TITLE
Support for FN-Link Hi1131s / 3131A-S (wifi)

### ISSUE THREAD

**Issue by videgro** [ZigFisher/openipc-1.0#2]
I bought the smart doorbell:
https://www.dx.com/p/b30-wireless-wi-fi-intercom-video-doorbell-b10-doorbell-receiver-set-2093215#.XJZ9J0Mo-Wg

It is working very well, but it is connecting to a cloud service in China, I would like to connect locally without transmission of audio/video via the Internet.

What I found so far is that it is based on the Hi3518EV200 chip.

I think this in an article about the development (use Google translate):
https://blog.csdn.net/qq_42448904/article/details/81178754

For WIFI it is using the FN-Link Hi1131s / 3131A-S.

Besides of that there is a MCU STM8L

See drawing in original Chinese post. The author (maybe developer?) is: qq_115369006 @ blog.csdn.net

I can't create an account at blog.csdn.net so I can't contact the developer or find more info at csdn.

I was successful in finding the Rx- Tx-pins at the PCB. After connecting via a serial-USB cable I can see the original booting process: it runs 'Huawei LiteOS' as operating system and I will end up at the prompt. I can also break the booting so I get the U-boot prompt and load via the SD-card (MMC) your chaos_calmer release from 2019.02.17 (openwrt-hisilicon-armv5tej-3.4.35-initramfs-uImage) ! Great!

But Wifi is not working and I also don't see any effect of pressing the doorbell. Normally it should send a 433Mhz signal and maybe also a notification to the OS.

Could you maybe help to integrate FN-Link Hi1131s / 3131A-S in the build?

Hope you can give me some hints how to integrate wifi and the MCU STM8L ?

Thanks in advance!

**Comment by ZigFisher** [comment]
Good day.
At the moment there is no WiFi support in our firmware, but we are working on it. As for the buttons, RF transmitters, microphone, speaker, and everything else - this is very specific and necessarily requires the presence of the device from the developer.
